# Site wide configuration

title:            gsahmad.com
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Ghazi Shazan Ahmad
  avatar: IMG_20191027_205808_Bokeh.jpg
  
  bio: "I am an undergrad student at International Institue of Information Technology, Bangalore. I am interested in Machine Learning, Neural Networks and its application in Cognitive Science."
  email: ghazishazan.ahmad@iiitb.ac.in
  disqus-shortname:
  twitter: ShazanGhazi
  facebook: #
#   google: 
#     plus: 
#     scholar: https://scholar.google.com.tr/citations?user=iqa9qNYAAAAJ
#     analytics:
#     verify:
#     ad-client:
#     ad-slot:
  bing-verify:
  github: khufia
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ghazi-shazan-ahmad-89138517a
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
