# Site wide configuration

title:            gsahmad.com
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Oguz Kaya
  avatar: bio-photo.jpg
  bio: "I am an assistant professor (maître de conférences) in the ParSys team of Laboratoire de Recherche en Informatique (LRI) at Université Paris-Sud/Paris-Saclay. My research addresses combinatorial and computational problems arising in (multi)linear algebra, machine learning, and scientific computing."
  email: oguz.kaya@lri.fr
  disqus-shortname:
  twitter: #username
  facebook: kayaogz
  google: 
    plus: 
    scholar: https://scholar.google.com.tr/citations?user=iqa9qNYAAAAJ
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kayaogz
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: kayaogz
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
